HOSTS:
  oel7:
    roles:
      - server
      - default
      - master
      - simp_server
      - el7
    platform:   el-7-x86_64
    box:        elastic/oel-7-x86_64
    hypervisor: vagrant
    yum_repos:
      epel:
        mirrorlist: 'https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch'
        gpgkeys:
          - https://getfedora.org/static/352C64E5.txt
      simp:
        baseurl: 'https://packagecloud.io/simp-project/6_X/el/$releasever/$basearch'
        gpgkeys:
          - https://raw.githubusercontent.com/NationalSecurityAgency/SIMP/master/GPGKEYS/RPM-GPG-KEY-SIMP
          - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP-6
      simp_dependencies:
        baseurl: 'https://packagecloud.io/simp-project/6_X_Dependencies/el/$releasever/$basearch'
        gpgkeys:
          - https://raw.githubusercontent.com/NationalSecurityAgency/SIMP/master/GPGKEYS/RPM-GPG-KEY-SIMP
          - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP-6
          - https://yum.puppetlabs.com/RPM-GPG-KEY-puppetlabs
          - https://yum.puppetlabs.com/RPM-GPG-KEY-puppet
          - https://apt.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG-94
          - https://getfedora.org/static/352C64E5.txt

  oel6:
    roles:
      - simp_server
    platform:   el-6-x86_64
    box:        elastic/oel-6-x86_64
    hypervisor: vagrant
    yum_repos:
      epel:
        mirrorlist: 'https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch'
        gpgkeys:
          - https://getfedora.org/static/352C64E5.txt
      simp:
        baseurl: 'https://packagecloud.io/simp-project/6_X/el/$releasever/$basearch'
        gpgkeys:
          - https://raw.githubusercontent.com/NationalSecurityAgency/SIMP/master/GPGKEYS/RPM-GPG-KEY-SIMP
          - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP-6
      simp_dependencies:
        baseurl: 'https://packagecloud.io/simp-project/6_X_Dependencies/el/$releasever/$basearch'
        gpgkeys:
          - https://raw.githubusercontent.com/NationalSecurityAgency/SIMP/master/GPGKEYS/RPM-GPG-KEY-SIMP
          - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP-6
          - https://yum.puppetlabs.com/RPM-GPG-KEY-puppetlabs
          - https://yum.puppetlabs.com/RPM-GPG-KEY-puppet
          - https://apt.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG-94
          - https://getfedora.org/static/352C64E5.txt

CONFIG:
  log_level: verbose
  type:      aio
  vagrant_memsize: 256
  synced_folder: disabled
  # vb_gui: true
