---
fixtures:
  repositories:
    acpid: https://github.com/simp/pupmod-simp-acpid
    activemq: https://github.com/simp/pupmod-simp-activemq
    aide: https://github.com/simp/pupmod-simp-aide
    auditd: https://github.com/simp/pupmod-simp-auditd
    augeasproviders:
      repo: https://github.com/simp/augeasproviders
      branch: simp-master
    augeasproviders_base:
      repo: https://github.com/simp/augeasproviders_base
      branch: simp-master
    augeasproviders_core:
      repo: https://github.com/simp/augeasproviders_core
      branch: simp-master
    augeasproviders_grub:
      repo: https://github.com/simp/augeasproviders_grub
      branch: simp-master
    augeasproviders_puppet:
      repo: https://github.com/simp/augeasproviders_puppet
      branch: simp-master
    augeasproviders_apache:
      repo: https://github.com/simp/augeasproviders_apache
      branch: simp-master
    augeasproviders_mounttab:
      repo: https://github.com/simp/augeasproviders_mounttab
      branch: simp-master
    augeasproviders_nagios:
      repo: https://github.com/simp/augeasproviders_nagios
      branch: simp-master
    augeasproviders_pam:
      repo: https://github.com/simp/augeasproviders_pam
      branch: simp-master
    augeasproviders_postgresql:
      repo: https://github.com/simp/augeasproviders_postgresql
      branch: simp-master
    augeasproviders_shellvar:
      repo: https://github.com/simp/augeasproviders_shellvar
      branch: simp-master
    augeasproviders_ssh:
      repo: https://github.com/simp/augeasproviders_ssh
      branch: simp-master
    augeasproviders_sysctl:
      repo: https://github.com/simp/augeasproviders_sysctl
      branch: simp-master
    autofs: https://github.com/simp/pupmod-simp-autofs
    clamav: https://github.com/simp/pupmod-simp-clamav
    concat: https://github.com/simp/puppetlabs-concat
    datacat:
      repo: https://github.com/simp/puppet-datacat
      branch: simp-master
    dhcp: https://github.com/simp/pupmod-simp-dhcp
    freeradius: https://github.com/simp/pupmod-simp-freeradius
    ganglia: https://github.com/simp/pupmod-simp-ganglia
    haveged:
      repo: https://github.com/simp/puppet-haveged
      branch: simp-master
    inifile:
      repo: https://github.com/simp/puppetlabs-inifile
      branch: simp-master
    iptables: https://github.com/simp/pupmod-simp-iptables
    java:
      repo: https://github.com/simp/puppetlabs-java
      branch: simp-master
    java_ks:
      repo: https://github.com/simp/puppetlabs-java_ks
      branch: simp-master
    kmod: https://github.com/simp/puppet-kmod.git
    krb5: https://github.com/simp/pupmod-simp-krb5
    logrotate: https://github.com/simp/pupmod-simp-logrotate
    mcollective:
      repo: https://github.com/simp/pupmod-simp-mcollective
      branch: simp-master
    named: https://github.com/simp/pupmod-simp-named
    nfs: https://github.com/simp/pupmod-simp-nfs
    ntpd: https://github.com/simp/pupmod-simp-ntpd
    oddjob: https://github.com/simp/pupmod-simp-oddjob
    openldap:
      repo: https://github.com/jeannegreulich/pupmod-simp-openldap
      branch: SIMP-2180
    pam: https://github.com/simp/pupmod-simp-pam
    pki: https://github.com/simp/pupmod-simp-pki
    postfix: https://github.com/simp/pupmod-simp-postfix
    postgresql: https://github.com/simp/puppetlabs-postgresql
    puppetdb:
      repo: https://github.com/simp/puppetlabs-puppetdb
      branch: simp-master
    file_concat: https://github.com/simp/puppet-lib-file_concat
    pupmod: https://github.com/simp/pupmod-simp-pupmod
    rsync:
      repo: https://github.com/trevor-vaughan/pupmod-simp-rsync
      branch: SIMP-1695
    rsyslog: https://github.com/simp/pupmod-simp-rsyslog
    selinux: https://github.com/simp/pupmod-simp-selinux
    simpcat: https://github.com/simp/pupmod-simp-concat
    simplib: https://github.com/simp/pupmod-simp-simplib
    simp_apache: https://github.com/simp/pupmod-simp-apache
    snmpd: https://github.com/simp/pupmod-simp-snmpd
    ssh: https://github.com/simp/pupmod-simp-ssh
    stdlib: https://github.com/simp/puppetlabs-stdlib
    stunnel: https://github.com/simp/pupmod-simp-stunnel
    sssd: https://github.com/simp/pupmod-simp-sssd
    sudo: https://github.com/simp/pupmod-simp-sudo
    sudosh: https://github.com/simp/pupmod-simp-sudosh
    svckill: https://github.com/simp/pupmod-simp-svckill
    tcpwrappers: https://github.com/simp/pupmod-simp-tcpwrappers
    tftpboot: https://github.com/simp/pupmod-simp-tftpboot
    upstart: https://github.com/simp/pupmod-simp-upstart
    xinetd: https://github.com/simp/pupmod-simp-xinetd

    resolv: https://github.com/simp/pupmod-simp-resolv
    cron: https://github.com/simp/pupmod-simp-cron
    tuned: https://github.com/simp/pupmod-simp-tuned
    at: https://github.com/simp/pupmod-simp-at
    useradd: https://github.com/simp/pupmod-simp-useradd
    incron: https://github.com/simp/pupmod-simp-incron
    chkrootkit: https://github.com/simp/pupmod-simp-chkrootkit
    fips: https://github.com/simp/pupmod-simp-fips
    swap: https://github.com/simp/pupmod-simp-swap
    motd:
      repo: https://github.com/simp/puppetlabs-motd
      branch: simp-master
    nsswitch:
      repo: https://github.com/simp/puppet-nsswitch
      branch: simp-master
    issue: https://github.com/simp/pupmod-simp-issue
  symlinks:
    simp: "#{source_dir}"
