---
fixtures:
  repositories:
    # Kluge for testing the automatic cert generation
    # Note: Ideally, would like to name this 'environment', to match
    # the name of the component in a simp-core Puppetfile.  However,
    # pluginsync on the VMs barfs with a module named 'environment'
    simp_environment: https://github.com/simp/simp-environment-skeleton
    # End Kluge
    acpid: https://github.com/simp/pupmod-simp-acpid
    aide: https://github.com/simp/pupmod-simp-aide
    auditd: https://github.com/simp/pupmod-simp-auditd
    at: https://github.com/simp/pupmod-simp-at
    augeas_core:
      repo: https://github.com/simp/pupmod-puppetlabs-augeas_core.git
      puppet_version: ">= 6.0.0"
    augeasproviders_apache: https://github.com/simp/augeasproviders_apache
    augeasproviders_core: https://github.com/simp/augeasproviders_core
    augeasproviders_grub: https://github.com/simp/augeasproviders_grub
    augeasproviders_mounttab: https://github.com/simp/augeasproviders_mounttab
    augeasproviders_nagios: https://github.com/simp/augeasproviders_nagios
    augeasproviders_pam: https://github.com/simp/augeasproviders_pam
    augeasproviders_postgresql: https://github.com/simp/augeasproviders_postgresql
    augeasproviders_puppet: https://github.com/simp/augeasproviders_puppet
    augeasproviders_shellvar: https://github.com/simp/augeasproviders_shellvar
    augeasproviders_ssh: https://github.com/simp/augeasproviders_ssh
    augeasproviders_sysctl: https://github.com/simp/augeasproviders_sysctl
    autofs: https://github.com/simp/pupmod-simp-autofs
    chkrootkit: https://github.com/simp/pupmod-simp-chkrootkit
    clamav: https://github.com/simp/pupmod-simp-clamav
    compliance_markup: https://github.com/simp/pupmod-simp-compliance_markup
    concat: https://github.com/simp/puppetlabs-concat
    cron: https://github.com/simp/pupmod-simp-cron
    cron_core:
      repo: https://github.com/simp/pupmod-puppetlabs-cron_core.git
      puppet_version: ">= 6.0.0"
    deferred_resources: https://github.com/simp/pupmod-simp-deferred_resources
    datacat: https://github.com/simp/puppet-datacat
    dhcp: https://github.com/simp/pupmod-simp-dhcp
    fips: https://github.com/simp/pupmod-simp-fips
    haveged: https://github.com/simp/pupmod-simp-haveged
    hocon: https://github.com/simp/pupmod-puppetlabs-hocon
    host_core:
      repo: https://github.com/simp/pupmod-puppetlabs-host_core.git
      puppet_version: ">= 6.0.0"
    incron: https://github.com/simp/pupmod-simp-incron
    inifile: https://github.com/simp/puppetlabs-inifile
    iptables: https://github.com/simp/pupmod-simp-iptables
    issue: https://github.com/simp/pupmod-simp-issue
    java: https://github.com/simp/puppetlabs-java
    kmod: https://github.com/simp/puppet-kmod.git
    krb5: https://github.com/simp/pupmod-simp-krb5
    logrotate: https://github.com/simp/pupmod-simp-logrotate
    motd: https://github.com/simp/puppetlabs-motd
    mount_core:
      repo: https://github.com/simp/pupmod-puppetlabs-mount_core.git
      puppet_version: ">= 6.0.0"
    named: https://github.com/simp/pupmod-simp-named
    nfs: https://github.com/simp/pupmod-simp-nfs
    nsswitch: https://github.com/simp/puppet-nsswitch
    ntpd: https://github.com/simp/pupmod-simp-ntpd
    oddjob: https://github.com/simp/pupmod-simp-oddjob
    pam: https://github.com/simp/pupmod-simp-pam
    pki: https://github.com/simp/pupmod-simp-pki
    polkit: https://github.com/simp/pupmod-simp-polkit
    postfix: https://github.com/simp/pupmod-simp-postfix
    postgresql:
      repo: https://github.com/simp/puppetlabs-postgresql
      ref: 5.12.1
    puppetdb:
      repo: https://github.com/simp/puppetlabs-puppetdb
      ref: 7.1.0
    pupmod: https://github.com/simp/pupmod-simp-pupmod
    puppet_authorization:
      repo: https://github.com/simp/puppetlabs-puppet_authorization
      ref: 0.5.0
    resolv: https://github.com/simp/pupmod-simp-resolv
    rkhunter: https://github.com/simp/pupmod-simp-rkhunter
    rsync: https://github.com/simp/pupmod-simp-rsync
    rsyslog: https://github.com/simp/pupmod-simp-rsyslog
    selinux: https://github.com/simp/pupmod-simp-selinux
    selinux_core:
      repo: https://github.com/simp/pupmod-puppetlabs-selinux_core.git
      puppet_version: ">= 6.0.0"
    simpcat: https://github.com/simp/pupmod-simp-concat
    simplib: https://github.com/simp/pupmod-simp-simplib
    simp_apache: https://github.com/simp/pupmod-simp-apache
    simp_banners: https://github.com/simp/pupmod-simp-simp_banners
    simp_openldap: https://github.com/simp/pupmod-simp-simp_openldap
    simp_options: https://github.com/simp/pupmod-simp-simp_options
    simp_rsyslog: https://github.com/simp/pupmod-simp-simp_rsyslog
    ssh: https://github.com/simp/pupmod-simp-ssh
    sshkeys_core:
      repo: https://github.com/simp/pupmod-puppetlabs-sshkeys_core.git
      puppet_version: ">= 6.0.0"
    sssd: https://github.com/simp/pupmod-simp-sssd
    stdlib: https://github.com/simp/puppetlabs-stdlib
    stunnel: https://github.com/simp/pupmod-simp-stunnel
    systemd:
      repo: https://github.com/simp/puppet-systemd
      branch: simp-master
    sudo: https://github.com/simp/pupmod-simp-sudo
    sudosh: https://github.com/simp/pupmod-simp-sudosh
    svckill: https://github.com/simp/pupmod-simp-svckill
    swap: https://github.com/simp/pupmod-simp-swap
    tcpwrappers: https://github.com/simp/pupmod-simp-tcpwrappers
    tftpboot: https://github.com/simp/pupmod-simp-tftpboot
    timezone: https://github.com/simp/pupmod-simp-timezone
    tlog: https://github.com/simp/pupmod-simp-tlog
    tuned: https://github.com/simp/pupmod-simp-tuned
    upstart: https://github.com/simp/pupmod-simp-upstart
    useradd: https://github.com/simp/pupmod-simp-useradd
    vox_selinux:
      repo: https://github.com/simp/pupmod-voxpupuli-selinux
      branch: simp-master
    xinetd: https://github.com/simp/pupmod-simp-xinetd
    yum: https://github.com/simp/voxpupuli-yum
    yumrepo_core:
      repo: https://github.com/simp/pupmod-puppetlabs-yumrepo_core.git
      puppet_version: ">= 6.0.0"
    # Kluge for rsync data
    '../acceptance/rsync_shares/simp': https://github.com/simp/simp-rsync-skeleton
  symlinks:
    simp: "#{source_dir}"
