---
fixtures:
  repositories:
    acpid: "git://github.com/simp/pupmod-simp-acpid"
    activemq: "git://github.com/simp/pupmod-simp-activemq"
    aide: "git://github.com/simp/pupmod-simp-aide"
    apache: "git://github.com/simp/pupmod-simp-apache"
    auditd: "git://github.com/simp/pupmod-simp-auditd"
    augeasproviders:             "git://github.com/simp/augeasproviders"
    augeasproviders_base:        "git://github.com/simp/augeasproviders_base"
    augeasproviders_core:        "git://github.com/simp/augeasproviders_core"
    augeasproviders_grub:        "git://github.com/simp/augeasproviders_grub"
    augeasproviders_puppet:      "git://github.com/simp/augeasproviders_puppet"
    augeasproviders_apache:      "git://github.com/simp/augeasproviders_apache"
    augeasproviders_mounttab:    "git://github.com/simp/augeasproviders_mounttab"
    augeasproviders_nagios:      "git://github.com/simp/augeasproviders_nagios"
    augeasproviders_pam:         "git://github.com/simp/augeasproviders_pam"
    augeasproviders_postgresql:  "git://github.com/simp/augeasproviders_postgresql"
    augeasproviders_shellvar:    "git://github.com/simp/augeasproviders_shellvar"
    augeasproviders_ssh:         "git://github.com/simp/augeasproviders_ssh"
    augeasproviders_sysctl:      "git://github.com/simp/augeasproviders_sysctl"
    autofs: "git://github.com/simp/pupmod-simp-autofs"
    clamav: "git://github.com/simp/pupmod-simp-clamav"
    datacat: "git://github.com/simp/puppet-datacat"
    compliance: "https://github.com/trevor-vaughan/pupmod-compliance"
    dhcp: "git://github.com/simp/pupmod-simp-dhcp"
    freeradius: "git://github.com/simp/pupmod-simp-freeradius"
    ganglia: "git://github.com/simp/pupmod-simp-ganglia"
    inifile: "git://github.com/simp/puppetlabs-inifile"
    iptables: "git://github.com/simp/pupmod-simp-iptables"
    java: "git://github.com/simp/puppetlabs-java"
    java_ks: "git://github.com/simp/puppetlabs-java_ks"
    logrotate: "git://github.com/simp/pupmod-simp-logrotate"
    mcollective: "git://github.com/simp/pupmod-simp-mcollective"
    named: "git://github.com/simp/pupmod-simp-named"
    nfs: "git://github.com/simp/pupmod-simp-nfs"
    nscd: "git://github.com/simp/pupmod-simp-nscd"
    ntpd: "git://github.com/simp/pupmod-simp-ntpd"
    oddjob: "git://github.com/simp/pupmod-simp-oddjob"
    openldap: "git://github.com/simp/pupmod-simp-openldap"
    pam: "git://github.com/simp/pupmod-simp-pam"
    pki: "git://github.com/simp/pupmod-simp-pki"
    postfix: "git://github.com/simp/pupmod-simp-postfix"
    pupmod: "git://github.com/simp/pupmod-simp-pupmod"
    rsync: "git://github.com/simp/pupmod-simp-rsync"
    rsyslog: "git://github.com/simp/pupmod-simp-rsyslog"
    selinux: "git://github.com/simp/pupmod-simp-selinux"
    simpcat: "git://github.com/simp/pupmod-simp-concat"
    simplib: "git://github.com/simp/pupmod-simp-simplib"
    snmpd: "git://github.com/simp/pupmod-simp-snmpd"
    ssh: "git://github.com/simp/pupmod-simp-ssh"
    stdlib: "git://github.com/simp/puppetlabs-stdlib"
    stunnel: "git://github.com/simp/pupmod-simp-stunnel"
    sssd: "git://github.com/simp/pupmod-simp-sssd"
    sudo: "git://github.com/simp/pupmod-simp-sudo"
    sudosh: "git://github.com/simp/pupmod-simp-sudosh"
    svckill: "git://github.com/simp/pupmod-simp-svckill"
    sysctl: "git://github.com/simp/pupmod-simp-sysctl"
    tcpwrappers: "git://github.com/simp/pupmod-simp-tcpwrappers"
    tftpboot: "git://github.com/simp/pupmod-simp-tftpboot"
    upstart: "git://github.com/simp/pupmod-simp-upstart"
    xinetd: "git://github.com/simp/pupmod-simp-xinetd"
  symlinks:
    simp: "#{source_dir}"
