<%
  if ENV['BEAKER_HYPERVISOR']
    hypervisor = ENV['BEAKER_HYPERVISOR']
  else
    hypervisor = 'vagrant'
  end
-%>
HOSTS:
  server-el7.simp.beaker:
    roles:
      - server
      - default
      - ldap_server
      - openldap
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: <%= hypervisor %>

  server-el8.simp.beaker:
    roles:
      - server
      - ldap_server
      - ds389
    platform:   el-8-x86_64
    box:        centos/8
    hypervisor: <%= hypervisor %>

  client-el7.simp.beaker:
    roles:
      - client
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: <%= hypervisor %>

  client-el8.simp.beaker:
    roles:
      - client
    platform:   el-8-x86_64
    box:        centos/8
    hypervisor: <%= hypervisor %>

CONFIG:
  log_level: verbose
  type: aio
  vagrant_memsize: 2048
  synced_folder: disabled
<% if ENV['BEAKER_PUPPET_COLLECTION'] -%>
  puppet_collection: <%= ENV['BEAKER_PUPPET_COLLECTION'] %>
<% end -%>
