HOSTS:
  server5:
    roles:
      - server
      - default
      - master
      - simp_server
      - nfs_server
      - mco_server
      - el7
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: vagrant
    yum_repos:
      epel:
        mirrorlist: 'https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch'
        gpgkeys:
          - https://getfedora.org/static/352C64E5.txt
      simp:
        baseurl: https://dl.bintray.com/simp/5.1.X
        gpgcheck: 0

  client5:
    roles:
      - client
      - agent
      - el7
      - mco_client
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: vagrant
    yum_repos:
      epel:
        mirrorlist: 'https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch'
        gpgkeys:
          - https://getfedora.org/static/352C64E5.txt
      simp:
        baseurl: https://dl.bintray.com/simp/5.1.X
        gpgcheck: 0

  server4:
    roles:
      - simp_server
      - nfs_server
      - el6
      - mco_server
    platform:   el-6-x86_64
    box:        centos/6
    hypervisor: vagrant
    yum_repos:
      epel:
        mirrorlist: 'https://mirrors.fedoraproject.org/metalink?repo=epel-6&arch=$basearch'
        gpgkeys:
          - https://getfedora.org/static/0608B895.txt
      simp:
        baseurl: https://dl.bintray.com/simp/4.2.X
        gpgcheck: 0

  client4:
    roles:
      - client
      - agent
      - el6
      - mco_client
    platform:   el-6-x86_64
    box:        centos/6
    hypervisor: vagrant
    yum_repos:
      epel:
        mirrorlist: 'https://mirrors.fedoraproject.org/metalink?repo=epel-6&arch=$basearch'
        gpgkeys:
          - https://getfedora.org/static/0608B895.txt
      simp:
        baseurl: https://dl.bintray.com/simp/4.2.X
        gpgcheck: 0

CONFIG:
  log_level: verbose
  type:      aio
  vagrant_memsize: 2048
  # vb_gui: true
