<%
  if ENV['BEAKER_HYPERVISOR']
    hypervisor = ENV['BEAKER_HYPERVISOR']
  else
    hypervisor = 'vagrant'
  end
-%>
HOSTS:
  server-el7.simp.beaker:
    roles:
      - server
      - default
      - master
      - simp_server
      - el7
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: <%= hypervisor %>
    yum_repos:
      updates:
        baseurl: 'http://mirror.centos.org/centos/$releasever/os/$basearch/'
        gpgkeys:
          - https://www.centos.org/keys/RPM-GPG-KEY-CentOS-7

      simp:
        baseurl: https://download.simp-project.com/simp/yum/rolling/6/el/$releasever/$basearch/simp
        gpgkeys:
          - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP
          - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP-6
          - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-SIMP-UNSTABLE
      simp_epel:
        baseurl: https://download.simp-project.com/simp/yum/rolling/6/el/$releasever/$basearch/epel
        gpgkeys:
          - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-CentOS-$releasever
          - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-redhat-release
          - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-EPEL-$releasever
      simp_postgresql:
        baseurl: https://download.simp-project.com/simp/yum/rolling/6/el/$releasever/$basearch/postgresql
        gpgkeys:
          - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-PGDG-96
      simp_puppet:
        baseurl: https://download.simp-project.com/simp/yum/rolling/6/el/$releasever/$basearch/puppet
        gpgkeys:
          - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-puppet
          - https://download.simp-project.com/simp/GPGKEYS/RPM-GPG-KEY-puppetlabs


CONFIG:
  log_level: verbose
  type: aio
<% if ENV['BEAKER_PUPPET_COLLECTION'] -%>
  puppet_collection: <%= ENV['BEAKER_PUPPET_COLLECTION'] %>
<% end -%>
